import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <header>
          <nav>
            <h1>
              <Link href='/'>Quiz App</Link>
            </h1>
            <ul>
              <li>
                <Link href='/'>Home</Link>
              </li>
              <li>
                <Link href='/question'>Question</Link>
              </li>
              <li>
                <Link href='/state'>State</Link>
              </li>
              <li>
                <Link href='/quiz'>Quiz</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className='wrap'>{children}</div>
        <footer>footer</footer>
      </body>
    </html>
  );
}
